export const permissionsMap = [
  {
    category: 'pages',
    categoryLabel: 'صفحات التطبيق',
    permissions: [
      { id: 'view_dashboard', label: 'عرض لوحة التحكم' },
      { id: 'view_products_page', label: 'عرض صفحة المنتجات' },
      { id: 'view_orders_page', label: 'عرض صفحة الطلبات' },
      { id: 'view_inventory_page', label: 'عرض صفحة المخزون' },
      { id: 'view_purchases_page', label: 'عرض صفحة المشتريات' },
      { id: 'view_accounting_page', label: 'عرض صفحة المحاسبة' },
      { id: 'view_profits_page', label: 'عرض صفحة الأرباح' },
      { id: 'view_employees_page', label: 'عرض صفحة الموظفين' },
      { id: 'view_settings_page', label: 'عرض صفحة الإعدادات' },
      { id: 'view_notifications_page', label: 'عرض صفحة الإشعارات' },
      { id: 'view_manage_products_page', label: 'عرض صفحة إدارة المنتجات' },
      { id: 'view_manage_variants_page', label: 'عرض صفحة إدارة المتغيرات' },
      { id: 'view_add_product_page', label: 'عرض صفحة إضافة منتج' },
      { id: 'view_barcode_inventory_page', label: 'عرض صفحة جرد الباركود' },
      { id: 'view_quick_order_page', label: 'عرض صفحة الطلب السريع' }
    ]
  },
  {
    category: 'products',
    categoryLabel: 'المنتجات والمخزن',
    permissions: [
      { id: 'view_products', label: 'عرض المنتجات' },
      { id: 'view_inventory', label: 'عرض الجرد والمخزون' },
      { id: 'use_barcode_scanner', label: 'استخدام قارئ الباركود' },
      { id: 'manage_products', label: 'إدارة المنتجات (إضافة/تعديل/حذف)' },
      { id: 'edit_product_quantities', label: 'تعديل كميات المخزون يدوياً' },
      { id: 'manage_categories', label: 'إدارة التصنيفات والمتغيرات' },
      { id: 'view_all_classifications', label: 'عرض جميع التصنيفات' },
      { id: 'view_all_categories', label: 'عرض جميع الفئات' },
      { id: 'view_all_sizes', label: 'عرض جميع الأحجام' },
      { id: 'view_all_colors', label: 'عرض جميع الألوان' },
      { id: 'print_labels', label: 'طباعة الملصقات' },
      { id: 'export_inventory', label: 'تصدير المخزون' },
      { id: 'import_products', label: 'استيراد المنتجات' }
    ]
  },
  {
    category: 'orders',
    categoryLabel: 'الطلبات والمبيعات',
    permissions: [
      { id: 'view_orders', label: 'عرض الطلبات' },
      { id: 'create_orders', label: 'إنشاء طلبات جديدة' },
      { id: 'edit_orders', label: 'تعديل الطلبات' },
      { id: 'cancel_orders', label: 'إلغاء الطلبات' },
      { id: 'view_sales_analytics', label: 'عرض تحليلات المبيعات' },
      { id: 'process_returns', label: 'معالجة المرتجعات' },
      { id: 'quick_order', label: 'الطلبات السريعة' },
      { id: 'checkout_orders', label: 'إتمام الطلبات' },
      { id: 'view_order_details', label: 'عرض تفاصيل الطلبات' },
      { id: 'print_invoices', label: 'طباعة الفواتير' }
    ]
  },
  {
    category: 'purchases',
    categoryLabel: 'المشتريات والموردين',
    permissions: [
      { id: 'view_purchases', label: 'عرض المشتريات' },
      { id: 'create_purchases', label: 'إنشاء مشتريات جديدة' },
      { id: 'edit_purchases', label: 'تعديل المشتريات' },
      { id: 'delete_purchases', label: 'حذف المشتريات' },
      { id: 'view_suppliers', label: 'عرض الموردين' },
      { id: 'manage_suppliers', label: 'إدارة الموردين' },
      { id: 'view_purchase_analytics', label: 'عرض تحليلات المشتريات' }
    ]
  },
  {
    category: 'accounting',
    categoryLabel: 'المحاسبة والتقارير',
    permissions: [
      { id: 'view_financial_reports', label: 'عرض التقارير المالية' },
      { id: 'view_profit_summary', label: 'عرض ملخص الأرباح' },
      { id: 'manage_expenses', label: 'إدارة المصروفات' },
      { id: 'view_pending_dues', label: 'عرض المستحقات المعلقة' },
      { id: 'settle_dues', label: 'تسوية المستحقات' },
      { id: 'export_reports', label: 'تصدير التقارير' },
      { id: 'profit_settlement', label: 'تسوية الأرباح' },
      { id: 'settlement_invoices', label: 'فواتير التسوية' },
      { id: 'view_profits', label: 'عرض الأرباح' }
    ]
  },
  {
    category: 'employees',
    categoryLabel: 'إدارة الموظفين',
    permissions: [
      { id: 'view_employees', label: 'عرض الموظفين' },
      { id: 'manage_employees', label: 'إدارة الموظفين' },
      { id: 'manage_employee_profits', label: 'إدارة أرباح الموظفين' },
      { id: 'view_employee_performance', label: 'عرض أداء الموظفين' },
      { id: 'update_permissions', label: 'تحديث الصلاحيات' },
      { id: 'employee_follow_up', label: 'متابعة الموظفين' },
      { id: 'edit_employee_details', label: 'تعديل بيانات الموظفين' }
    ]
  },
  {
    category: 'system',
    categoryLabel: 'إعدادات النظام',
    permissions: [
      { id: 'manage_settings', label: 'إدارة إعدادات النظام' },
      { id: 'view_notifications', label: 'عرض الإشعارات' },
      { id: 'manage_notifications', label: 'إدارة الإشعارات' },
      { id: 'view_system_logs', label: 'عرض سجلات النظام' },
      { id: 'backup_restore', label: 'النسخ الاحتياطي والاستعادة' },
      { id: 'ai_features', label: 'استخدام ميزات الذكاء الاصطناعي' },
      { id: 'appearance_settings', label: 'إعدادات المظهر' },
      { id: 'security_settings', label: 'إعدادات الأمان' },
      { id: 'profile_settings', label: 'إعدادات الملف الشخصي' }
    ]
  },
  {
    category: 'dashboard',
    categoryLabel: 'لوحة التحكم',
    permissions: [
      { id: 'view_statistics', label: 'عرض الإحصائيات' },
      { id: 'view_charts', label: 'عرض الرسوم البيانية' },
      { id: 'view_recent_activities', label: 'عرض الأنشطة الحديثة' },
      { id: 'view_alerts', label: 'عرض التنبيهات' },
      { id: 'manage_ai_orders', label: 'إدارة طلبات الذكاء الاصطناعي' }
    ]
  }
];

// Default permissions for each role
export const defaultPermissions = {
  employee: [
    'view_dashboard',
    'view_products_page',
    'view_orders_page',
    'view_inventory_page',
    'view_products',
    'view_inventory',
    'view_orders',
    'create_orders',
    'quick_order',
    'checkout_orders',
    'view_order_details',
    'view_statistics',
    'view_recent_activities'
  ],
  warehouse: [
    'view_dashboard',
    'view_products_page',
    'view_inventory_page',
    'view_purchases_page',
    'view_barcode_inventory_page',
    'view_products',
    'view_inventory',
    'use_barcode_scanner',
    'edit_product_quantities',
    'view_purchases',
    'create_purchases',
    'view_statistics',
    'view_recent_activities'
  ],
  deputy: [
    'view_dashboard',
    'view_products_page',
    'view_orders_page',
    'view_inventory_page',
    'view_purchases_page',
    'view_accounting_page',
    'view_profits_page',
    'view_manage_products_page',
    'view_quick_order_page',
    'view_products',
    'view_inventory',
    'view_orders',
    'create_orders',
    'edit_orders',
    'view_sales_analytics',
    'quick_order',
    'checkout_orders',
    'view_order_details',
    'view_purchases',
    'create_purchases',
    'edit_purchases',
    'view_financial_reports',
    'view_profit_summary',
    'manage_products',
    'edit_product_quantities',
    'use_barcode_scanner',
    'view_statistics',
    'view_charts',
    'view_recent_activities',
    'view_alerts'
  ],
  admin: [
    // All permissions - admins have access to everything
    'view_dashboard',
    'view_products_page',
    'view_orders_page', 
    'view_inventory_page',
    'view_purchases_page',
    'view_accounting_page',
    'view_profits_page',
    'view_employees_page',
    'view_settings_page',
    'view_notifications_page',
    'view_manage_products_page',
    'view_manage_variants_page',
    'view_add_product_page',
    'view_barcode_inventory_page',
    'view_quick_order_page',
    'view_products',
    'view_inventory',
    'use_barcode_scanner',
    'manage_products',
    'edit_product_quantities',
    'manage_categories',
    'view_all_classifications',
    'view_all_categories',
    'view_all_sizes',
    'view_all_colors',
    'print_labels',
    'export_inventory',
    'import_products',
    'view_orders',
    'create_orders',
    'edit_orders',
    'cancel_orders',
    'view_sales_analytics',
    'process_returns',
    'quick_order',
    'checkout_orders',
    'view_order_details',
    'print_invoices',
    'view_purchases',
    'create_purchases',
    'edit_purchases',
    'delete_purchases',
    'view_suppliers',
    'manage_suppliers',
    'view_purchase_analytics',
    'view_financial_reports',
    'view_profit_summary',
    'manage_expenses',
    'view_pending_dues',
    'settle_dues',
    'export_reports',
    'profit_settlement',
    'settlement_invoices',
    'view_profits',
    'view_employees',
    'manage_employees',
    'manage_employee_profits',
    'view_employee_performance',
    'update_permissions',
    'employee_follow_up',
    'edit_employee_details',
    'manage_settings',
    'view_notifications',
    'manage_notifications',
    'view_system_logs',
    'backup_restore',
    'ai_features',
    'appearance_settings',
    'security_settings',
    'profile_settings',
    'view_statistics',
    'view_charts',
    'view_recent_activities',
    'view_alerts',
    'manage_ai_orders'
  ]
}
];