#!/bin/bash
# تشغيل vite مباشرة من node_modules
if [ -f "./node_modules/vite/bin/vite.js" ]; then
    exec node ./node_modules/vite/bin/vite.js "$@"
elif [ -f "./node_modules/.bin/vite" ]; then
    exec ./node_modules/.bin/vite "$@"
else
    exec npx vite "$@"
fi