-- تحويل جميع delivery_status النصية إلى أرقام في جدول orders
-- هذا يوحد التخزين ويحل مشكلة المزامنة

UPDATE orders
SET delivery_status = CASE 
  -- الحالات الأساسية
  WHEN delivery_status = 'معطل او غير فعال' THEN '0'
  WHEN delivery_status = 'فعال ( قيد التجهير)' THEN '1'
  WHEN delivery_status = 'فعال' THEN '1'
  WHEN delivery_status = 'تم الاستلام من قبل المندوب' THEN '2'
  WHEN delivery_status = 'قيد التوصيل الى الزبون (في عهدة المندوب)' THEN '3'
  WHEN delivery_status = 'قيد التوصيل للزبون (في عهدة المندوب)' THEN '3'
  WHEN delivery_status = 'تم التسليم للزبون' THEN '4'
  WHEN delivery_status = 'تم تسليم جزء من المنتجات' THEN '5'
  WHEN delivery_status = 'في الطريق الى مكتب المحافظة' THEN '6'
  WHEN delivery_status = 'في مكتب المحافظة' THEN '7'
  WHEN delivery_status = 'لا يرد' THEN '8'
  WHEN delivery_status = 'لا يرد بعد الاتفاق' THEN '9'
  WHEN delivery_status = 'مغلق' THEN '10'
  WHEN delivery_status = 'مغلق بعد الاتفاق' THEN '11'
  WHEN delivery_status = 'مؤجل' THEN '12'
  WHEN delivery_status = 'مؤجل لحين اعادة الطلب لاحقا' THEN '13'
  WHEN delivery_status = 'الغاء الطلب' THEN '14'
  WHEN delivery_status = 'رفض الطلب' THEN '15'
  WHEN delivery_status = 'تم تغيير محافظة الزبون' THEN '16'
  WHEN delivery_status = 'تم الارجاع الى التاجر' THEN '17'
  WHEN delivery_status = 'مفصول عن الخدمة' THEN '18'
  WHEN delivery_status = 'طلب مكرر' THEN '19'
  WHEN delivery_status = 'مستلم مسبقا' THEN '20'
  WHEN delivery_status = 'الرقم غير معرف' THEN '21'
  WHEN delivery_status = 'الرقم غير داخل في الخدمة' THEN '22'
  WHEN delivery_status = 'ارسال الى مخزن الارجاعات' THEN '23'
  WHEN delivery_status = 'العنوان غير دقيق' THEN '24'
  WHEN delivery_status = 'لم يطلب' THEN '25'
  WHEN delivery_status = 'حظر المندوب' THEN '26'
  WHEN delivery_status = 'لا يمكن الاتصال بالرقم' THEN '27'
  WHEN delivery_status = 'تغيير المندوب' THEN '28'
  WHEN delivery_status = 'تم الارجاع من المخزن وتسليمها الى التاجر' THEN '29'
  WHEN delivery_status = 'الراجعات في الطريق الى المخزن' THEN '30'
  WHEN delivery_status = 'تم تحويل الطلب الى مندوب اخر' THEN '31'
  WHEN delivery_status = 'في الطريق الى مكتب المحافظة لاحقا' THEN '32'
  WHEN delivery_status = 'في الطريق الى المكتب في البداية' THEN '33'
  WHEN delivery_status = 'في مكتب بغداد' THEN '34'
  WHEN delivery_status = 'الطلب جاهز للاستلام من قبل المندوب' THEN '35'
  WHEN delivery_status = 'فعال قيد الانتظار للتأكد من المعلومات' THEN '36'
  WHEN delivery_status = 'راجعات بالمخزن' THEN '37'
  WHEN delivery_status = 'راجعات تم ارجاعها لطرف ثالث' THEN '38'
  WHEN delivery_status = 'اعادة التسليم' THEN '39'
  WHEN delivery_status = 'راجعات بالمكتب' THEN '40'
  WHEN delivery_status = 'راجعات التاجر في مخزن الشركة' THEN '41'
  WHEN delivery_status = 'الراجعات في الطريق الى المخزن ضمن سيارة بغداد' THEN '42'
  WHEN delivery_status = 'راجع الى التاجر بشكل جزئي' THEN '43'
  -- Fallback للنصوص غير المطابقة بدقة
  WHEN delivery_status LIKE '%قيد التوصيل%زبون%' THEN '3'
  WHEN delivery_status LIKE '%تسليم%زبون%' THEN '4'
  WHEN delivery_status LIKE '%ارجاع%تاجر%' THEN '17'
  WHEN delivery_status LIKE '%مخزن%ارجاع%' THEN '23'
  ELSE delivery_status
END
WHERE delivery_partner = 'alwaseet'
  AND delivery_status IS NOT NULL
  AND delivery_status !~ '^\d+$';  -- فقط النصوص، ليس الأرقام