-- تطبيع جميع delivery_status النصية إلى أرقام للطلبات من الوسيط
UPDATE orders
SET delivery_status = CASE 
  WHEN delivery_status = 'معطل او غير فعال' THEN '0'
  WHEN delivery_status = 'فعال ( قيد التجهير)' THEN '1'
  WHEN delivery_status = 'تم الاستلام من قبل المندوب' THEN '2'
  WHEN delivery_status = 'قيد التوصيل الى الزبون (في عهدة المندوب)' THEN '3'
  WHEN delivery_status = 'تم التسليم للزبون' THEN '4'
  WHEN delivery_status = 'في موقع فرز بغداد' THEN '5'
  WHEN delivery_status = 'في مكتب' THEN '6'
  WHEN delivery_status = 'في الطريق الى مكتب المحافظة' THEN '7'
  WHEN delivery_status = 'في مخزن مرتجع المحافظة' THEN '12'
  WHEN delivery_status = 'في مخزن مرتجع بغداد' THEN '13'
  WHEN delivery_status = 'اعادة الارسال الى الزبون' THEN '14'
  WHEN delivery_status = 'ارجاع الى التاجر' THEN '15'
  WHEN delivery_status = 'قيد الارجاع الى التاجر (في عهدة المندوب)' THEN '16'
  WHEN delivery_status = 'تم الارجاع الى التاجر' THEN '17'
  WHEN delivery_status = 'تغيير سعر' THEN '18'
  WHEN delivery_status = 'ارجاع بعد الاستلام' THEN '19'
  WHEN delivery_status = 'تبديل بعد التوصيل' THEN '20'
  WHEN delivery_status = 'تم التسليم للزبون واستلام منة الاسترجاع' THEN '21'
  WHEN delivery_status = 'ارسال الى الفزر' THEN '22'
  WHEN delivery_status = 'ارسال الى مخزن الارجاعات' THEN '23'
  WHEN delivery_status = 'تم تغيير محافظة الزبون' THEN '24'
  WHEN delivery_status = 'لا يرد' THEN '25'
  WHEN delivery_status = 'لا يرد بعد الاتفاق' THEN '26'
  WHEN delivery_status = 'مغلق' THEN '27'
  WHEN delivery_status = 'مغلق بعد الاتفاق' THEN '28'
  WHEN delivery_status = 'مؤجل' THEN '29'
  WHEN delivery_status = 'مؤجل لحين اعادة الطلب لاحقا' THEN '30'
  WHEN delivery_status = 'الغاء الطلب' THEN '31'
  WHEN delivery_status = 'رفض الطلب' THEN '32'
  WHEN delivery_status = 'مفصول عن الخدمة' THEN '33'
  WHEN delivery_status = 'طلب مكرر' THEN '34'
  WHEN delivery_status = 'مستلم مسبقا' THEN '35'
  WHEN delivery_status = 'الرقم غير معرف' THEN '36'
  WHEN delivery_status = 'الرقم غير داخل في الخدمة' THEN '37'
  WHEN delivery_status = 'العنوان غير دقيق' THEN '38'
  WHEN delivery_status = 'لم يطلب' THEN '39'
  WHEN delivery_status = 'حظر المندوب' THEN '40'
  WHEN delivery_status = 'لا يمكن الاتصال بالرقم' THEN '41'
  WHEN delivery_status = 'تغيير المندوب' THEN '42'
  WHEN delivery_status = 'اخراج من المخزن وارسالة الى الفرز' THEN '44'
  ELSE delivery_status
END
WHERE delivery_partner = 'alwaseet'
  AND delivery_status !~ '^\d+$';