-- إصلاح schema لـ regions_master و cities_master
-- المشكلة: id و alwaseet_id كانت NOT NULL بدون default
-- الحل: id يصبح auto-increment، و alwaseet_id يصبح nullable

-- تحويل id إلى IDENTITY (auto-increment)
DO $$
DECLARE
  max_regions_id INTEGER;
  max_cities_id INTEGER;
BEGIN
  -- regions_master
  SELECT COALESCE(MAX(id), 0) INTO max_regions_id FROM public.regions_master;
  ALTER TABLE public.regions_master ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval(pg_get_serial_sequence('public.regions_master', 'id'), GREATEST(max_regions_id, 1));
  
  -- cities_master
  SELECT COALESCE(MAX(id), 0) INTO max_cities_id FROM public.cities_master;
  ALTER TABLE public.cities_master ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  PERFORM setval(pg_get_serial_sequence('public.cities_master', 'id'), GREATEST(max_cities_id, 1));
END $$;

-- جعل alwaseet_id nullable (مدن وغيرها لا تستخدمه)
ALTER TABLE public.regions_master ALTER COLUMN alwaseet_id DROP NOT NULL;
ALTER TABLE public.cities_master ALTER COLUMN alwaseet_id DROP NOT NULL;

-- تنظيف التوكنات المنتهية المكررة
DELETE FROM public.delivery_partner_tokens 
WHERE is_active = false 
  AND expires_at < now()
  AND (
    (partner_name = 'alwaseet' AND account_username IN ('alshmry94', 'ryusiq')) 
    OR (partner_name = 'modon' AND account_username = 'lab@ryus-brand')
  );