// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  }
});

// ✅ تجديد الجلسة عند العودة للتاب — يحافظ على تسجيل الدخول طويلاً
if (typeof window !== 'undefined') {
  document.addEventListener('visibilitychange', () => {
    if (!document.hidden) {
      // فحص الجلسة وتجديدها عند الحاجة (لا يُرمى خطأ إن لم يكن مسجلاً)
      supabase.auth.getSession().then(({ data }) => {
        if (data?.session) {
          // إذا كانت الجلسة على وشك الانتهاء (<5 دقائق)، جدّدها
          const expiresAt = data.session.expires_at;
          if (expiresAt) {
            const msLeft = expiresAt * 1000 - Date.now();
            if (msLeft < 5 * 60 * 1000) {
              supabase.auth.refreshSession().catch(() => {});
            }
          }
        }
      }).catch(() => {});
    }
  });
}

